version: "3.4"

services:
  LabDeputy:
    image: "eling486/lab_deputy:latest"
    container_name: "lab_deputy"
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "./:/app/data"
    network_mode: bridge
    environment:
      - TZ=Asia/Shanghai
      - PGID=1000
      - PUID=1000
      - UMASK=022