const lang = {
    attr: 'EN',
    msg_err: 'An error occurred, please try again',
    msg_err_reload: 'An error occurred, please refresh and try again',
    msg_err_not_admin: 'Insufficient permissions',
    msg_click_to_copy: 'Click to copy',
    msg_click_to_edit: 'Click to edit',
    msg_copy_success: 'Copied to clipboard',
    msg_click_to_open_in_blank: 'Open in new tab',
    reconfirmation: 'Reconfirmation',
    confirm: 'Confirm',
    cancel: 'Cancel',
    save: 'Save',
    reset: 'Reset',
    delete: 'Delete',
    general: {
        login: 'Login',
        register: 'Register',
        username: 'Username',
        realname: 'Real Name',
        equipment: 'Equipment',
        hour_attr: 'hr'
    },
    header: {
        home: 'Home',
        booking: 'Booking',
        storage: 'Storage',
        manage: 'Manage',
        setting: 'Settings',
        logout: 'Logout'
    },
    home: {
        title: 'Home',
        welcome: 'Welcome to LabDeputy',
        msg_welcome: 'Welcome to LabDeputy. You can book equipment, manage inventory, etc. here.',
        msg_no_data: 'No data available',
        msg_no_booking: 'No bookings',
        msg_no_storage: 'No inventory',
    },
    login: {
        login: 'Login',
        register: 'Register',
        username: 'Username',
        realname: 'Real Name',
        password: 'Password',
        password_repeat: 'Confirm Password',
        msg_need_username: 'Please enter username',
        msg_need_realname: 'Please enter real name',
        msg_need_password: 'Please enter password',
        msg_need_repeat_password: 'Please repeat password',
        msg_error_password_repeat: 'Repeated passwords are different',
        msg_error_password_illegal: 'Password must be at least 6 characters and contain both letters and numbers',
        msg_success_register: 'Registration successful! Redirecting to login page'
    },
    booking: {
        epuipment_placeholder: 'Select an Equipment',
        booking_tips: 'Please click and drag in the time table',
        booking_list: 'Book the following time periods:',
        booking: 'Book',
        prev_week: 'Previous Week',
        next_week: 'Next Week',
        msg_success_booked: 'Successfully booked',
        msg_error_booking: 'Booking failed',
        msg_error_time_clash: 'Time Clash',
    },
    setting: {
        uid: 'User ID',
        username: 'Username',
        realname: 'Real Name',
        password_old: 'Old Password',
        password: 'New Password',
        password_repeat: 'Confirm Password',
        reset: 'Reset',
        save: 'Save',
        alert_change_password: 'Change Password',
        alert_change_realname: 'Change Real Name',
        msg_error_empty_realname: 'Please enter real name',
        msg_error_empty_old_password: 'Please enter old password',
        msg_err_old_password: 'Incorrect old password',
        msg_error_password_repeat: 'Repeated passwords are different',
        msg_error_password_illegal: 'Password must be at least 6 characters and contain both letters and numbers',
        msg_save_success: 'Settings saved successfully',
        msg_save_success_reload: 'Settings saved successfully. You will be logged out in 5 seconds',
    },
    manage: {
        nav_user: 'User Management',
        invite_count: 'Invitation Count',
        generate_invitation: 'Generate Invitation Link',
        generate_invitation_confirm: 'Are you sure you want to generate an invitation link?',
        invitation_link_title: 'Invitation Link (click to select)',
        alert_invite_user: 'Invite New Member'
    }
}

export default lang