const lang = {
    attr: '简',
    msg_err: '发生错误，请重试',
    msg_err_reload: '发生错误，请刷新重试',
    msg_err_not_admin: '权限不足',
    msg_click_to_copy: '点击复制',
    msg_click_to_edit: '点击编辑',
    msg_copy_success: '已添加到剪贴板',
    msg_click_to_open_in_blank: '新标签页中打开',
    confirm: '确定',
    cancel: '取消',
    save: '保存',
    reset: '重置',
    delete: '删除',
    header: {
        home: '首页',
        booking: '预约',
        storage: '库存',
        admin: '管理',
        setting: '设置',
        logout: '登出'
    },
    home: {
        title: '首页',
        welcome: '欢迎使用实验室助手',
        msg_welcome: '欢迎使用实验室助手，您可以在这里预约设备、管理库存等。',
        msg_no_data: '暂无数据',
        msg_no_booking: '暂无预约',
        msg_no_storage: '暂无库存',
    },
    login: {
        login: '登录',
        username: '用户名',
        password: '密码',
        msg_need_username: '请输入用户名',
        msg_need_password: '请输入密码',
    },
    setting: {
        uid: '用户ID',
        username: '用户名',
        realname: '真实姓名',
        password_old: '原密码',
        password: '新密码',
        password_repeat: '确认密码',
        reset: '重置',
        save: '保存',
        alert_change_password: '修改密码',
        alert_change_realname: '修改真实姓名',
        msg_error_empty_realname: '请输入真实姓名',
        msg_error_empty_old_password: '请输入原密码',
        msg_err_old_password: '原密码错误',
        msg_error_password_repeat: '两次输入的新密码不一致',
        msg_error_password_illegal: '密码需至少6位，包含字母及数字',
        msg_save_success: '设置保存成功',
        msg_save_success_reload: '设置保存成功，将在5秒后登出',
    }
}

export default lang